"""Tests for new features: patient creation fix, doctor management,
visit reports, patient medical info (allergies)."""
import pytest
from django.urls import reverse

from app.models import (
    Patient, Clients, UserProfile, PatientMedicalInfo, VisitReport,
)


pytestmark = pytest.mark.django_db


# ──────────────────────────────────────────────────────────────────────────────
# Patient creation fix (card_number + user_id)
# ──────────────────────────────────────────────────────────────────────────────

class TestPatientCardNumber:
    def test_card_number_autogenerated_on_save(self):
        """При создании пациента без явного card_number он генерируется автоматически с префиксом K-."""
        # Arrange
        # Act
        p = Patient.objects.create(
            full_name='Безномерный Пациент',
            birth_date='1990-01-01 00:00:00',
            gender='M', phone='+79990000001',
        )

        # Assert
        assert p.card_number
        assert p.card_number.startswith('K-')

    def test_card_numbers_are_unique_sequential(self):
        """Два разных пациента получают уникальные номера карт."""
        # Arrange / Act
        p1 = Patient.objects.create(
            full_name='Первый', birth_date='1990-01-01 00:00:00',
            gender='M', phone='+79990000002',
        )
        p2 = Patient.objects.create(
            full_name='Второй', birth_date='1990-01-01 00:00:00',
            gender='M', phone='+79990000003',
        )

        # Assert
        assert p1.card_number != p2.card_number

    def test_explicit_card_number_preserved(self):
        """Если card_number задан явно, он не перезаписывается при сохранении."""
        # Arrange / Act
        p = Patient.objects.create(
            card_number='K-2000-99999',
            full_name='Свой Номер', birth_date='1990-01-01 00:00:00',
            gender='F', phone='+79990000004',
        )

        # Assert
        assert p.card_number == 'K-2000-99999'


class TestPatientCreateView:
    def test_manager_creates_patient_fills_card_and_user(self, client, user_manager):
        """Менеджер создаёт пациента через форму — у пациента заполняются card_number и user_id."""
        # Arrange
        client.force_login(user_manager)

        # Act
        r = client.post(reverse('app:patient_create'), {
            'full_name': 'Новый Пациент Тестов',
            'birth_date': '1992-02-02',
            'gender': 'M',
            'phone': '+79991234567',
        })

        # Assert
        assert r.status_code == 302
        p = Patient.objects.get(full_name='Новый Пациент Тестов')
        assert p.card_number             # сгенерирован
        assert p.user_id                 # создан связанный Clients
        assert Clients.objects.filter(id=p.user_id, role='patient').exists()


# ──────────────────────────────────────────────────────────────────────────────
# Doctor management
# ──────────────────────────────────────────────────────────────────────────────

class TestDoctorCreate:
    URL = None

    def test_manager_can_open_doctor_form(self, client, user_manager):
        """Менеджер открывает форму создания врача — статус 200."""
        # Arrange
        client.force_login(user_manager)

        # Act
        r = client.get(reverse('app:doctor_create'))

        # Assert
        assert r.status_code == 200

    def test_dentist_cannot_open_doctor_form(self, client, user_dentist):
        """Стоматолог не имеет доступа к форме создания врача — статус 302 или 403."""
        # Arrange
        client.force_login(user_dentist)

        # Act
        r = client.get(reverse('app:doctor_create'))

        # Assert
        assert r.status_code in (302, 403)

    def test_manager_creates_doctor(self, client, user_manager):
        """Менеджер создаёт нового врача-стоматолога — пользователь сохраняется с ролью dentist."""
        # Arrange
        from django.contrib.auth.models import User
        client.force_login(user_manager)

        # Act
        r = client.post(reverse('app:doctor_create'), {
            'username': 'newdentist1',
            'first_name': 'Пётр', 'last_name': 'Зубов',
            'email': 'p@clinic.com', 'password': 'pass1234',
            'specialization': 'Ортодонт', 'cabinet': '3', 'phone': '+79990001122',
        })

        # Assert
        assert r.status_code == 302
        user = User.objects.get(username='newdentist1')
        assert user.profile.role == 'dentist'
        assert user.profile.specialization == 'Ортодонт'
        assert Clients.objects.filter(login='newdentist1', role='dentist').exists()

    def test_duplicate_username_rejected(self, client, user_manager, user_dentist):
        """Попытка создать врача с уже существующим логином возвращает форму с ошибкой (200)."""
        # Arrange
        client.force_login(user_manager)

        # Act
        r = client.post(reverse('app:doctor_create'), {
            'username': user_dentist.username,
            'first_name': 'X', 'last_name': 'Y', 'password': 'pass1234',
        })

        # Assert
        assert r.status_code == 200  # форма с ошибкой, без редиректа

    def test_doctor_list_renders(self, client, user_manager, user_dentist):
        """Страница списка врачей отображается для менеджера — статус 200."""
        # Arrange
        client.force_login(user_manager)

        # Act
        r = client.get(reverse('app:doctor_list'))

        # Assert
        assert r.status_code == 200


# ──────────────────────────────────────────────────────────────────────────────
# Patient medical info (allergies)
# ──────────────────────────────────────────────────────────────────────────────

class TestPatientMedicalInfo:
    def test_has_alerts_property(self, patient):
        """Свойство has_alerts возвращает True, если у пациента есть аллергии."""
        # Arrange
        info = PatientMedicalInfo.objects.create(patient=patient, allergies='Лидокаин')

        # Act / Assert
        assert info.has_alerts is True

    def test_no_alerts_when_empty(self, patient):
        """Свойство has_alerts возвращает False, если поле allergies пустое."""
        # Arrange
        info = PatientMedicalInfo.objects.create(patient=patient, blood_type='A+')

        # Act / Assert
        assert info.has_alerts is False

    def test_dentist_can_open_medical_info(self, client, user_dentist, patient):
        """Стоматолог открывает страницу медицинской информации пациента — статус 200."""
        # Arrange
        client.force_login(user_dentist)

        # Act
        r = client.get(reverse('app:patient_medical_info', args=[patient.pk]))

        # Assert
        assert r.status_code == 200

    def test_dentist_can_save_medical_info(self, client, user_dentist, patient):
        """Стоматолог сохраняет медицинскую информацию пациента — данные записываются в БД."""
        # Arrange
        client.force_login(user_dentist)

        # Act
        r = client.post(reverse('app:patient_medical_info', args=[patient.pk]), {
            'allergies': 'Пенициллин',
            'chronic_conditions': 'Диабет',
            'contraindications': '',
            'blood_type': 'O+',
            'notes': '',
        })

        # Assert
        assert r.status_code == 302
        info = PatientMedicalInfo.objects.get(patient=patient)
        assert info.allergies == 'Пенициллин'
        assert info.blood_type == 'O+'

    def test_update_existing_medical_info(self, client, user_dentist, patient):
        """Повторное сохранение медицинской информации обновляет существующую запись (не создаёт дубликат)."""
        # Arrange
        PatientMedicalInfo.objects.create(patient=patient, allergies='Старое')
        client.force_login(user_dentist)

        # Act
        r = client.post(reverse('app:patient_medical_info', args=[patient.pk]), {
            'allergies': 'Новое', 'chronic_conditions': '', 'contraindications': '',
            'blood_type': '', 'notes': '',
        })

        # Assert
        assert r.status_code == 302
        assert PatientMedicalInfo.objects.filter(patient=patient).count() == 1
        assert PatientMedicalInfo.objects.get(patient=patient).allergies == 'Новое'

    def test_history_shows_allergy_alert(self, client, user_dentist, patient):
        """Страница истории пациента отображает его аллергии из медицинской информации."""
        # Arrange
        PatientMedicalInfo.objects.create(patient=patient, allergies='Латекс')
        client.force_login(user_dentist)

        # Act
        r = client.get(reverse('app:patient_history', args=[patient.pk]))

        # Assert
        assert r.status_code == 200
        assert 'Латекс' in r.content.decode()

    def test_manager_cannot_edit_medical_info(self, client, user_manager, patient):
        """Менеджер не имеет доступа к редактированию медицинской информации — статус 302 или 403."""
        # Arrange
        client.force_login(user_manager)

        # Act
        r = client.get(reverse('app:patient_medical_info', args=[patient.pk]))

        # Assert
        assert r.status_code in (302, 403)


# ──────────────────────────────────────────────────────────────────────────────
# Visit reports
# ──────────────────────────────────────────────────────────────────────────────

class TestVisitReport:
    def test_dentist_can_open_report_form(self, client, user_dentist, visit):
        """Стоматолог открывает форму отчёта о визите — статус 200."""
        # Arrange
        client.force_login(user_dentist)

        # Act
        r = client.get(reverse('app:visit_report', args=[visit.pk]))

        # Assert
        assert r.status_code == 200

    def test_dentist_can_write_report(self, client, user_dentist, visit):
        """Стоматолог успешно сохраняет отчёт о визите — объект VisitReport создаётся в БД."""
        # Arrange
        client.force_login(user_dentist)

        # Act
        r = client.post(reverse('app:visit_report', args=[visit.pk]), {
            'title': 'Отчёт о приёме',
            'summary': 'Проведено лечение кариеса.',
            'recommendations': 'Контроль через 6 мес.',
            'complications': '',
        })

        # Assert
        assert r.status_code == 302
        report = VisitReport.objects.get(visit=visit)
        assert report.summary.startswith('Проведено')
        assert report.author == user_dentist

    def test_report_requires_summary(self, client, user_dentist, visit):
        """Отчёт без поля summary не сохраняется — форма возвращается с ошибкой (200)."""
        # Arrange
        client.force_login(user_dentist)

        # Act
        r = client.post(reverse('app:visit_report', args=[visit.pk]), {
            'title': 'Без заключения', 'summary': '',
        })

        # Assert
        assert r.status_code == 200  # форма с ошибкой
        assert not VisitReport.objects.filter(visit=visit).exists()

    def test_str(self, visit, user_dentist):
        """Строковое представление VisitReport содержит слово «визит»."""
        # Arrange
        report = VisitReport.objects.create(
            visit=visit, author=user_dentist, summary='x',
        )

        # Act / Assert
        assert 'визит' in str(report).lower()

    def test_patient_cannot_write_report(self, client, user_patient, visit):
        """Пациент не имеет доступа к форме отчёта о визите — статус 302 или 403."""
        # Arrange
        client.force_login(user_patient)

        # Act
        r = client.get(reverse('app:visit_report', args=[visit.pk]))

        # Assert
        assert r.status_code in (302, 403)
